name: mcmc
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - emcee
  - joblib
  - pandas
  - jupyter
  - ca-certificates
  - certifi
  - openssl
  - tqdm
  - corner
  - tabulate
